### ISSUE TITLE
Sounds in Status

### ISSUE THREAD

**Issue by errorists** [status-im/design#11]
In the nearby future we plan to add sounds inside Status, for both notifications and user interactions.

Planned scope

- Notification (app closed)
- New account set up
- Message sent successfully (in a conversation)
- Message received (in a conversation, without variations for now)
- Signing transaction
- Receiving a transaction (app closed)
- Transaction request (app closed)
- Receiving a transaction (inside chat)
- Transaction request (inside chat)

This task will follow the progress of choosing and/or creating the right, branded, sounds.

Slack: `#wired-for-sound`
Prototype for previewing sounds
https://framer.cloud/WRyQz

<blockquote><img src="https://framer.cloud/WRyQz/2/framer/social-1200x630.png" width="48" align="right"><div><strong><a href="https://framer.cloud/WRyQz">Status Sounds</a></strong></div><div>To run on a phone, install the viewer app https://itunes.apple.com/app/id1124920547</div></blockquote>

**Comment by hesterbruikman** [comment]
Captured in https://github.com/status-im/status-react/issues/10468
