### ISSUE TITLE
Animation inside chat

### ISSUE THREAD

**Issue by errorists** [status-im/design#12]
The scope of this task is to design and document all animation and interactions that takes place inside chat. Since a lot of the UI is built with custom components without native counterparts, it's the perfect place to start using motion as a brand element. 

Some general ideas:

- If an interaction or animation is better defined as a global app-wide behaviour it should fall outside the scope of this task
- Use code to design animation where possible and fallback to Airbnb's Lottie for more elaborate animation like spinners, illustration etc

Progress will be updated in this prototype.  
https://framer.cloud/AQWdp/

Documentation and a comprehensive list of animation to follow

<blockquote><img src="https://framer.cloud/AQWdp/11/framer/social-1200x630.png" width="48" align="right"><div><strong><a href="https://framer.cloud/AQWdp/">statusChat</a></strong></div><div>This project was made with Framer, a design tool for turning original concepts into working prototypes.</div></blockquote>

**Comment by hesterbruikman** [comment]
captured in https://github.com/status-im/status-react/issues/5985
