### ISSUE TITLE
Design for docs.status.im

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/design#19]
Documentation is the # 1 biggest issue highlighted by developers across the ecosystem.

https://docs.status.im/

### Designs tasks
- Identify user goals and required primary and secondary actions on Landingpage.
- Identify potential entry points and navigation behavior.
- Develop visual assets (DApps, Web3, Mobile first, Embark use, etc).
- Update Status logo on landingpage and favicon.
- Wireframe layout and content hierarchy for landingpage.
- Component-level design of content (Header, Buttons, Principles/Statements, Content cards).
- Specify component behaviour: External links, Scroll, Search box, Status logo (Home).

Follow general behavior and components of https://design.status.im/ and https://status.im/incubate/ for consistency where possible.

@andytudhope can elaborate on:
- Vision for the site 
- What elements are needed
- Theme of the site: movement, a hero's journey in summary

<blockquote><img src="https://status.im/img/og_logo.png" width="48" align="right"><div><strong><a href="https://status.im/index.html">Status Technikon · Build the future of a new web</a></strong></div><div>Build the future of a new web</div></blockquote>

**Comment by andytudhope** [comment]
Let's get feedback from @rachelhamlin and @jeluard as well.

## User goals: 
1. Build Status and get contributing as fast and easily as possible.
2. Learn more about development, testing, research at Status and how to get involved.
(long term: 3. Ultimate knowledge repository for Status Studio.)

## Potential entry points
Likely best to work off the two buttons currently on the page as the main entry points.

## Visual Assets
Please note, this site is only about Status and our developer community - so has a fairly narrow scope for now. There will be a link (as currently) to the Embark docs on the main page, but it is not a main nav item. DApps, Web3 and Mobile assets would be great.

As I told @andmironov in our first call, the theme I'd like to see in this site is dynamic movement, the hero's journey, the grail quest, passing through all the rough edges of a constantly changing environment, learning about how things can be done better, and achieving a hard but entirely worthwhile goal. Some of the stuff referred to in this doc on the main page has been removed, but I wrote up the vision here: https://docs.google.com/document/d/1vMG-ZNbDeCcEzEAm52SqQxHmIpLGejf71FuwEsvbZ8w/edit?usp=sharing

<blockquote><div><strong><a href="https://docs.google.com/document/d/1vMG-ZNbDeCcEzEAm52SqQxHmIpLGejf71FuwEsvbZ8w/edit?usp=sharing">Google Docs - create and edit documents online, for free.</a></strong></div><div>Create a new document and edit with others at the same time -- from your computer, phone or tablet. Get stuff done with or without an internet connection. Use Docs to edit Word files. Free from Google.</div></blockquote>

**Comment by hesterbruikman** [comment]
Outdated
