### ISSUE TITLE
Flow design of ‘Invite friends’

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/design#2]
**# Flow design of ‘Invite friends’**

The Core app of Status includes social functionality such as messaging and transacting cryptocurrency. To enable this functionality it is essential that people can easily invite friends to use the app without losing focus of the original goal to send a message or transaction. 

In the current implementation of the Status app, people would share their public key or QR code via another messenger or email. This flow is functional for the scenario in which the other party already has the app installed. We need a flow and specification of what ideally happens when the other party does not have the app installed yet.

**## Tasks**

- Create a wireframe level flow to Invite friends to Status.
- Use the current ‘Invite friends’ entry points in the app
- Include shareable message with a deeplink to the App Store/Play store
- Investigate constraints for iOS and Android
- Identify alternative entry points

**## Deliverable**

- Diagram showing the Invite friend proces
- Wireframe flow with suggested UI patterns and copy

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Tokens: SNT: 5000.00
Contract address: [0x4df0b6dc7db6e0b7a1e2d0e525619c1afa989213](https://etherscan.io/address/0x4df0b6dc7db6e0b7a1e2d0e525619c1afa989213)
![QR Code](https://openbounty.status.im/qr/status-im/design/bounty/2/aca7316a3d7048b19dd66a91b64d7ef582f85dcc224910728ec6352555e8ad36/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by alescode** [comment]
I spent a couple of days on this task, researching the current state of the art in deep linking and invitation flows on Android and iOS. I'm aiming to balance Status's policy of collecting as little personal information as possible with the need to grow the userbase by reducing friction – there's **a lot of messenger competition**. Solutions that involved asking for access to the user's contacts or asking a new user whether he was invited were discarded. 

## Diagram and wireframe flow
This diagram is best experienced step-by-step, [as a slideshow that contains explanations and wireframes for each step](https://docs.google.com/presentation/d/1G2BYTX4UbEAQuJfZR7hFGJylgwjkfPCjUKY5wlQpo34/edit?usp=sharing). It's also available as an image [here](https://user-images.githubusercontent.com/202928/41597483-e1073c8c-73cd-11e8-8bf3-d01557292eb2.png).

This flow proposes a backend service to fingerprint devices hosted on invites.status.im, inspired by [Branch](https://branch.io/how-branch-links-work/). We can expect fingerprinting to work [about 75% of the time](https://docs.branch.io/pages/resources/matching/). The data gathered isn't extremely sensitive and can be discarded after the new user's onboarding.

### Constraints
- Matching should work on Android if the user opens the link using Chrome, but may fail if he uses another browser
- Matching should work on iOS if the user opens the link using Safari (which is highly likely, as it's always the default browser)

### Alternative entry point
To incentivize more users to invite their friends, we can add a permanent row to the top of the conversation list that serves as an entry point.

<img src="https://user-images.githubusercontent.com/202928/41599868-ab2c8476-73d4-11e8-87f1-af7288a7eec9.png" alt="Conversation list with invite on top" width="300px">

We could make this flow more interesting by allowing the user to record a message, a sticker, or a token transfer on Status that his recipient will only be able to see once he's signed up.

<img src="https://user-images.githubusercontent.com/202928/41600380-17e9845a-73d6-11e8-914c-0a0493cb3cc7.png" alt="Getting a CryptoKitty on WhatsApp" width="300px">

**Comment by hesterbruikman** [comment]
Looking into this @alegw !

**Comment by alescode** [comment]
Hi guys, any estimated check date for this?

**Comment by hesterbruikman** [comment]
Thanks for your patience @alegw and apologies for keeping you waiting! We are very happy with the work you did. It took some time for us to free up resources to continue work on this Invite friends flow ourselves and thereby properly assess your design input. 

Here's feedback from the team on your proposal:

> - Really like the suggestion for an added, integrated, entrypoint to the flow on the conversation list. We are investigating how to give this 'homescreen' a refresh altogether and will keep this in mind.
> - The suggestion to send a 'cryptokitty' or other asset with the invite hadn't come up before. We'll investigate the technical feasability.
> - On the core of the Invite friends flow: we have decided to move into a different direction that will not require a centralized backend service. This definitely comes with a UX trade-off as people will need to visit a deeplink to a given user after they've downloaded the app and it limits the feasability of say sending a cryptokitty. This decision flows directly from our value Decentralization.

https://hackmd.io/5jB9lWyIQpO8lG1cyLR8oA

Thanks for your detailed and insightful contributing @alegw ! 
 

_Will make sure we payout your bounty asap._

**Comment by alescode** [comment]
Thanks Hester! Glad I was able to contribute. Rock on!

**Comment by pablanopete** [comment]
Sent payment!

**Comment by debragail** [comment]
Is this closed or still open?

**Comment by pablanopete** [comment]
@andytudhope to be revoked, this bounty has been completed by @alescode
