### ISSUE TITLE
Introduce deep linking UI

### ISSUE THREAD

**Issue by errorists** [status-im/design#20]
Design UI and flows to allow sharing of deep links to chat channels, profiles and Dapps.

More on the topic https://wiki.status.im/Universal_Links

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://wiki.status.im/Universal_Links">Universal Links - Status Wiki</a></strong></div></blockquote>

**Comment by artignatev** [comment]
Awesome! Tested it, works very well. Will be added to Eth2.io

How it looks:
![trust](https://user-images.githubusercontent.com/6490508/44522237-95bde200-a6de-11e8-9aa9-83d673b8026f.png)

**Comment by denis-sharypin** [comment]
@artyomignatyev  hey Artyom, please use the right logo of Status https://github.com/status-im/design-guides

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/design-guides">status-im/design-guides</a></strong></div><div>Contribute to status-im/design-guides development by creating an account on GitHub.</div></blockquote>
