### ISSUE TITLE
Handbook appeareance/redesign

### ISSUE THREAD

**Issue by Stefchi** [status-im/design#24]
Could anyone help to get

https://handbook.status.im/

Aligned with our branding (as in https://status.im/ )? Would love for it to have the same appearance and fonts. 

As we keep adding content, some navigation/UI advice would also be very welcome, to make sure the various sections are logically organized and easy to navigate.

<blockquote><div><strong><a href="https://sites.google.com/status.im/status-people-team">People at Status</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://status.im/">Status, a Mobile Ethereum OS</a></strong></div><div>Status is an interface to access Ethereum, built for Android & iOS. Enjoy encrypted messaging, a cryptocurrency wallet, and seamless access to DApps.</div></blockquote>

**Comment by Stefaniach** [comment]
OH WOW that had been a while 🤣 thanks @hesterbruikman

**Comment by hesterbruikman** [comment]
Blast from the past right?!


⁣Verzonden door TypeApp ​

Op 17 mrt. 2021 19:06, om 19:06, Stef ***@***.***> schreef:
