### ISSUE TITLE
UX test - Transaction phrase testing 

### ISSUE THREAD

**Issue by PhilipandWu** [status-im/design#27]
Main discussion and implementation convo moved here: 
https://github.com/status-im/status-react/pull/5824

**Research question and goal**

To solve the key highlighted issues related to transactions phrase identified in user testing (specific slide links included below):

* [users misunderstand tx phrase purpose](https://docs.google.com/presentation/d/1eJP-Hh4tN6XZREIy73GNuJP1LqGg41EvP5QpVlFZQ78/edit#slide=id.g3e1b33ca7e_2_157)
* [users do not need to copy emojis down, but only recognize](https://docs.google.com/presentation/d/1eJP-Hh4tN6XZREIy73GNuJP1LqGg41EvP5QpVlFZQ78/edit#slide=id.g3e1b33ca7e_2_168)

We want to qualitative understand how we can best communicate the risk of phishing without making users worried/shy to use the app

Recent slack discussion threads for further context:
*https://status-im.slack.com/archives/C813TET52/p1534502065000100
*https://status-im.slack.com/archives/C8QP8S5UH/p1534624372000100

**Proposed changes & Prototype**
* [Copy variations](https://docs.google.com/presentation/d/1cM7poT4Nl-Ckxdt6GOlLc8r2MeiINEVlu5kAL0k0RWw/edit#slide=id.g3e06642acc_0_0)
* [Prototype](https://www.figma.com/file/Xg0hHWg7Ngqrly2syl4MAM/Transaction-phrase-UXR?node-id=0%3A1)

**Study Approach**
* try to find 5-7 people quickly in 1-2 days (coffee shop/previous recruit list/media)
* Can either do quick-and-dirty or more formalized approach
* have participants download the app or use a test device to complete tasks
* Record with TechSmith if on an iOS device or Lookback for Android if possible
* Set up a notes schema to follow 

[WIP Script](https://docs.google.com/document/d/1W1bS7viArLXD74dFj7R_aAcwq_IgKD1dzRqkp5SDLq0/edit?ts=5b697c98)

**Ideal participant criteria**
* have not used status
*  somewhat familiar with crypto 
* use banking apps with similar phishing prevention or 2FA mechanism
* equal split between iOS and Android users 
* All have not participated in Status UX research over the last 3 months

**Planning**
Late August

**Preliminary findings**
* [preliminary TX study details](https://docs.google.com/document/d/1vyuyUqyn0g2sTQSN1SW263qFqH9QCxlMK8kz_Fi0w0Y/edit?ouid=105740245751601859065&usp=docs_home&ths=true)

**Comment by obi2020** [comment]
Please see some copy options on [these slides](https://docs.google.com/presentation/d/1cM7poT4Nl-Ckxdt6GOlLc8r2MeiINEVlu5kAL0k0RWw/edit?usp=sharing)

cc @denis-sharypin

**Comment by obi2020** [comment]
I focused on one wallet setup screen and the sign txn flow. If there's another place I'm missing, please point to it! Or we can discuss further in our sync tmr

**Comment by PhilipandWu** [comment]
@obi2020 There's also the copy at the send TX screen. It currently says secret transaction phrase so it should be updated too.

![38793894_2074409409298248_7524939043696541696_n](https://user-images.githubusercontent.com/40644582/43848410-dec085f0-9b00-11e8-8ae1-bcab7716eec8.jpg)
.

cc @denis-sharypin Also, should rearrange the visual hierarchy to reduce the chance that users think they have to reenter their emojis?


there's also the pop warning after. There was discussion on whether users need to record or just recognize it. The copy right now says record though again it's up for debate on how we approach this.

![38732191_434067443664293_1256530194689163264_n](https://user-images.githubusercontent.com/40644582/43848931-16180d42-9b02-11e8-8567-8577e722b188.jpg)

**Comment by errorists** [comment]
hey, just chiming in, it totally looks like the input is there to reenter emojis

**Comment by PhilipandWu** [comment]
@errorists exactly, me and @obi2020 encountered the same issue where we thought we had to reneter emojis. Some users from our tests were also confused.

 I'm not sure what the best approach is (emojis on top so the input feed isn't directly underneath?), but I'm open to your thoughts and Denis we can chat about it in our sync tmrw.

**Comment by errorists** [comment]
The more we do to visually separate them the better: change the order so that they're above the description, play with the border around them so that it's less similar to the rounded rectangle of the input, try a thin separator between to group them into two separate areas, I'm sure @denis-sharypin will think of more.

**Comment by hesterbruikman** [comment]
As the conversation about how to follow up testing is taking place here: https://github.com/status-im/status-react/pull/5824

Can we close the UX testing issue @PhilipandWu ?

**Comment by PhilipandWu** [comment]
@hesterbruikman yup! linked discussion in main thread as well.
