### ISSUE TITLE
Redesign pattern connection status and errors

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/design#28]
QA found an issue in that the currently used grey snackbar covers part of the clickable UI.
https://github.com/status-im/status-react/issues/5371

### Design tasks (TBD)

- [ ] Short term: Define behavior of the current pattern such that it doesn't limit user actions. (e.g. fade out, close, dynamic position). 
- [ ] Long term: Provide alternative patterns to indicate system Status (e.g. variations to the _new messages_ icon on the chat tab.

**Comment by denis-sharypin** [comment]
Hey, the current state of errors within the app:
![image](https://user-images.githubusercontent.com/6559881/43713902-1fa81c7a-9973-11e8-9dac-82d8ba9e215e.png)

**Comment by denis-sharypin** [comment]
Also I found a design spec for UI prioritization:
perharps we can use it here as a short term solution 
<img width="759" alt="screenshot 2018-08-06 12 22 25" src="https://user-images.githubusercontent.com/6559881/43714003-6e1714ec-9973-11e8-97e8-42552129a661.png">
 Link to Abstract https://share.goabstract.com/2d0b637a-3a41-4e74-9e60-ad689b4f3991

<blockquote><div><strong><a href="https://share.goabstract.com/2d0b637a-3a41-4e74-9e60-ad689b4f3991">Abstract</a></strong></div></blockquote>

**Comment by EugeOrtiz** [comment]
Please, let's think about this cross-platform (mobile + desktop) :-)
It would be great to also start differentiating what an error is vs confirmations, notifications, warnings, etc. They should be treated differently.
